import {useState} from 'react';
import {useAuth} from '../../app/auth';
import type {BrandDesign} from '../../lib/brand-design';
import {readNamedPresets,saveNamedPreset,deleteNamedPreset,exportWorkspacePreset,importWorkspacePreset} from '../../lib/workspace-presets';
export function WorkspacePresetTools({design,onChange,disabled=false}:{design:BrandDesign;onChange:(d:BrandDesign)=>void;disabled?:boolean}){
 const{user}=useAuth();const[name,setName]=useState('My look');const[revision,setRevision]=useState(0);const[message,setMessage]=useState('');const saved=readNamedPresets(user?.id);void revision;
 function act(fn:()=>void,text:string){try{fn();setRevision(x=>x+1);setMessage(text);}catch(e){setMessage(e instanceof Error?e.message:'Could not save this look.');}}
 return <details className="workspace-tune"><summary>Saved looks & backup <span>Save, import or export your design</span></summary><fieldset disabled={disabled}><label>Look name<input value={name} maxLength={40} onChange={e=>setName(e.target.value)}/></label><div className="workspace-preset-actions"><button type="button" onClick={()=>act(()=>saveNamedPreset(user?.id,{name,design}),'Look saved in this browser.')}>Save named look</button><button type="button" onClick={()=>act(()=>{const url=URL.createObjectURL(new Blob([exportWorkspacePreset(design,name)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='cardvault-look.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},'Appearance file downloaded.')}>Export look</button><label className="workspace-upload">Import look<input type="file" accept=".json,application/json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>4000000)throw Error('Choose a file smaller than 4 MB.');const p=importWorkspacePreset(await f.text());onChange(p.design);setName(p.name);setMessage('Look loaded. Review your settings before saving.');}catch(error){setMessage(error instanceof Error?error.message:'Could not import this file.');}e.target.value='';}}/></label></div>{saved.length>0&&<ul className="workspace-saved-looks">{saved.map(p=><li key={p.name}><span>{p.name}</span><button type="button" onClick={()=>{onChange(p.design);setMessage('Saved look loaded.');}}>Apply {p.name}</button><button type="button" onClick={()=>act(()=>deleteNamedPreset(user?.id,p.name),'Saved look removed.')}>Delete {p.name}</button></li>)}</ul>}<p>Saved looks stay in this browser for your account. Exports contain appearance settings and background images only.</p>{message&&<p role="status">{message}</p>}</fieldset></details>;
}
