import {DASHBOARD_MODULES,WORKSPACE_PRESETS,normalizeWorkspaceLayout,type WorkspaceLayout} from '../../lib/workspace-layout';
export function WorkspaceCustomizer({value,onChange,disabled=false,onPreset}:{value:WorkspaceLayout;onChange:(v:WorkspaceLayout)=>void;disabled?:boolean;onPreset?:(id:string)=>void}){
 function set<K extends keyof WorkspaceLayout>(key:K,next:WorkspaceLayout[K]){onChange({...value,[key]:next});}
 const labels={history:'Value history',recent:'Recent cards',decks:'Recent decks',sets:'Top sets',attention:'Needs attention'};
 return <fieldset className="workspace-customizer" disabled={disabled}><legend>Choose your workspace</legend><p>A starting point you can make your own. Every tool stays available.</p><div className="workspace-preset-grid">{WORKSPACE_PRESETS.map(p=><button type="button" key={p.id} aria-pressed={value.preset===p.id} className="workspace-preset" onClick={()=>onPreset?onPreset(p.id):onChange(normalizeWorkspaceLayout(p.layout))}><span className="workspace-preset-art" style={{background:p.colors[0],color:p.colors[1]}} aria-hidden="true"><i/><i/><i/></span><strong>{p.name}</strong><small>{p.detail}</small></button>)}</div>
 <details className="workspace-tune"><summary>Fine-tune layout <span>Navigation, spacing & card sizes</span></summary><div className="brand-design-grid">{([
 ['navigation','Main navigation',['side','top']],['sidebarWidth','Sidebar width',[220,260,300]],['density','Workspace spacing',['compact','comfortable','spacious']],['cardSize','Default card size',['small','medium','large']],['view','Default card view',['grid','list']],['logoSize','Logo size',[32,40,48,56]],
 ]as const).map(([key,label,values])=><label key={key}>{label}<select value={value[key]} onChange={e=>set(key,(typeof values[0]==='number'?Number(e.target.value):e.target.value) as never)}>{values.map(v=><option key={v} value={v}>{typeof v==='number'?`${v}px`:v[0].toUpperCase()+v.slice(1)}</option>)}</select></label>)}</div><button type="button" onClick={()=>onChange({...normalizeWorkspaceLayout(null),preset:value.preset,dashboardOrder:value.dashboardOrder,hiddenModules:value.hiddenModules})}>Reset layout controls</button></details>
 <details className="workspace-tune"><summary>Dashboard panels <span>Choose what you see and its order</span></summary><ol className="workspace-panel-order">{value.dashboardOrder.map((id,index)=><li key={id}><label><input type="checkbox" checked={!value.hiddenModules.includes(id)} onChange={e=>set('hiddenModules',e.target.checked?value.hiddenModules.filter(x=>x!==id):[...value.hiddenModules,id])}/>{labels[id]}</label><button type="button" aria-label={`Move ${labels[id]} up`} disabled={disabled||index===0} onClick={()=>{const order=[...value.dashboardOrder];[order[index-1],order[index]]=[order[index],order[index-1]];set('dashboardOrder',order);}}>↑</button><button type="button" aria-label={`Move ${labels[id]} down`} disabled={disabled||index===value.dashboardOrder.length-1} onClick={()=>{const order=[...value.dashboardOrder];[order[index+1],order[index]]=[order[index],order[index+1]];set('dashboardOrder',order);}}>↓</button></li>)}</ol><button type="button" onClick={()=>onChange({...value,dashboardOrder:[...DASHBOARD_MODULES],hiddenModules:[]})}>Restore all dashboard panels</button></details></fieldset>;
}
