import {useEffect,useRef,useState} from "react";
import {useLocation} from "react-router-dom";
import{readEffects,saveEffects,type WorkspaceEffects as Preferences}from"../lib/workspace-effects";
import "../styles/workspace-effects.css";
export function WorkspaceEffects(){const location=useLocation();const path=useRef(location.pathname);path.current=location.pathname;useEffect(()=>{
 const root=document.documentElement;let settings=readEffects();let context:AudioContext|null=null;let last=0;
 const update=()=>{settings=readEffects();root.dataset.effectsPower=settings.lowPower?"low":"full";root.dataset.effectsMotion=String(settings.motion&&!document.hidden&&!path.current.startsWith("/scan")&&!preference.matches);if(document.hidden&&context?.state==="running")void context.suspend();};
 const preference=typeof window.matchMedia === "function"?window.matchMedia("(prefers-reduced-motion: reduce)"):{matches:false,addEventListener:undefined,removeEventListener:undefined};
 const sound=(e:Event)=>{if(document.hidden)return;const hover=e.type==="pointerover";if(hover?!settings.hover:(!settings.clicks&&!settings.hover))return;const target=(e.target as Element)?.closest?.("button,a,select,input[type=checkbox],input[type=radio],summary");if(!target||target.hasAttribute("disabled"))return;if(hover&&target.contains((e as PointerEvent).relatedTarget as Node|null))return;const now=performance.now();if(now-last<(hover?180:65))return;last=now;
 if(hover&&!context)return;const AC=window.AudioContext;if(!AC)return;context??=new AC();if(!hover&&!settings.clicks){void context.resume().catch(()=>{});return;}void context.resume().then(()=>{if(!context||context.state!=="running")return;const osc=context.createOscillator(),g=context.createGain();osc.type="sine";osc.frequency.value=hover?520:780;g.gain.setValueAtTime(settings.volume*.07,context.currentTime);g.gain.exponentialRampToValueAtTime(.0001,context.currentTime+.06);osc.connect(g);g.connect(context.destination);osc.start();osc.stop(context.currentTime+.07);osc.onended=()=>{osc.disconnect();g.disconnect();};}).catch(()=>{});
 };
 update();window.addEventListener("workspace-effects",update);window.addEventListener("storage",update);document.addEventListener("visibilitychange",update);preference.addEventListener?.("change",update);document.addEventListener("pointerdown",sound);document.addEventListener("pointerover",sound);
 return()=>{window.removeEventListener("workspace-effects",update);window.removeEventListener("storage",update);document.removeEventListener("visibilitychange",update);preference.removeEventListener?.("change",update);document.removeEventListener("pointerdown",sound);document.removeEventListener("pointerover",sound);void context?.close();delete root.dataset.effectsMotion;};
 },[]);useEffect(()=>{window.dispatchEvent(new Event("workspace-effects"));},[location.pathname]);return <div className="workspace-ambient" aria-hidden="true"><i/><i/></div>;}
export function WorkspaceEffectsSettings(){const[s,set]=useState(readEffects);function update<K extends keyof Preferences>(key:K,value:Preferences[K]){const next={...s,[key]:value};set(next);saveEffects(next);}return <fieldset className="workspace-effects-settings"><legend>Motion & interface sounds</legend><p>Dynamic modes move gently in the background. Motion pauses while scanning or when this tab is hidden. Sounds start after your first click.</p><div>{([['motion','Moving backgrounds'],['lowPower','Low-power mode (recommended)'],['clicks','Click sounds'],['hover','Hover sounds']]as const).map(([key,label])=><label key={key}><input type="checkbox" checked={s[key]} onChange={e=>update(key,e.target.checked)}/>{label}</label>)}<label>Interface sound volume<input type="range" min="0" max="1" step=".05" value={s.volume} onChange={e=>update('volume',Number(e.target.value))}/></label></div></fieldset>;}
